
<div class="container">     
<div>
<div class="row" >
	<span class="span" ></span>
    
    <span class="span" ><a href="http://vk.com/club39644068" target="_blank">Наша группа ВК</a><br>
    <a href="http://vk.com/page-39644068_44341261" target="_blank">Как разместить объявление в группе</a>
    </span>
    <span class="span" ><a href="about.php">О проекте</a></span>
    <span class="span" ><a href="http://vk.com/mlarchenko" target="_blank">Обратная связь (ВК)</a><br>
    <a href="#">Вопросы и предложения</a></span>
    
    <span class="span" ><a href="#">Волонтерство</a><br>
    <a href="#">Сотрудничество</a></span>
    <span class="span" >
    </span></div>
<p>&copy; 2012 - <?=date('Y')?>. </p>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44687115-1', 'fondalma.org');
  ga('send', 'pageview');

</script>
</div>
</div>