<div id="header"><a href="index.php"><img src="img/logo.jpg" alt="Logo" style="float:left;"></a>
<p>
<a href="#">Благотворительная доска объявлений</a><br />
<a href="#">бесплатные объявления</a>, <a href="#">купить</a>, <a href="#">продать</a>, <a href="#">арендовать</a>, <a href="#">снять</a>, <a href="#">сдать</a>, <a href="#">заказать услуги</a><br />
<span><a href="#">и при этом помочь безнадзорным животным!</a></span></p>

    </div>
    </div>
    <div class="menubg">
    <div class="navbar container">  
  <div class="navbar-inner">  
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
        <span class="icon-bar"></span>  
      </a>  
      <div class="nav-collapse">   
       <ul class="nav">
                    <li class="active"><a href="index.php">Главная</a></li>
                    <!--<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                   Drop Down<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Item1</a></li>
                            <li><a href="#">Item2</a></li>
                            <li><a href="#">Item3</a></li>
                        </ul>
                    </li>-->  
                    <li class="bdr_rt"><a href="https://vk.com/club39644068" target="_blank">Наша группа</a></li>
                  </ul>
      </div>    
  </div>  
</div>
</div>
    <div class="container">
<div class="hero-unit"><a href="index.php"><img src="img/promo_v1.jpg" alt="Banner"></a> </div>